<h1 id="error-ldap-connects-with-django-but-login-is-still-unsuccessful">Error: Ldap connects with django but login is still unsuccessful</h1>
<h1 id="django-version-1.10.5-or-1.9.2">Django version: 1.10.5 or 1.9.2</h1>
<h2 id="ldap-connection-is-successful-but-user-cant-login-to-django-admin-panel">Ldap connection is successful but user can't login to Django admin panel</h2>
<p> Where ldap == openldap </p>
<p>As it turns out, connecting Django with Ldap is not as easy as it might seem.
I followed the <a href="https://pythonhosted.org/django-auth-ldap/index.html">documentation</a> exactly but still could not authenticate.</p>
<p>Then Google told me that my user had to be a member in all 3 Django groups(active, staff, superuser).
So I did that to. But still nothing.</p>
<p>I had logging enabled but the only thing shown there was &quot;Populating Django user test&quot; and nothing else. 
So it wasn't much of a help.</p>
<p>I found the issue when I decided to look at my sqlite database. Users were being stored correctly, with all their attributes etc.</p>
<p>But there was one error.</p>
<p>Previously one of my users had logged in perfectly. 
But I had used the def shown below to make him a django staff member.
</p>
<p>
Obviously he could not edit anything so I just made him a superuser instead. And it worked.</p>
<p>When I tried to do it a 2nd time, it failed, because the user no2 was a superuser but not a staff member.</p>
<b><p>Turns out he has to be both a superuser member and a staff member.</p>
<p>So I added the defs below to my models.py and it all worked.</p></b>
<pre><code>def make_super(sender, user, **kwargs): 
    user.is_superuser = True 

populate_user.connect(make_super)</code></pre>
<pre><code>def make_staff(sender, user, **kwargs):
    user.is_staff = True

populate_user.connect(make_staff)</code></pre>
<p>(defs were not made by me so no credits for that, I just can't seem to be able to find the author)</p>
